"""Generate the Wayfinder inner-ring tick keyframes into wayfinder.css.

Each tick is a short eased move with a slight overshoot, then a hold, like a
watch hand. CSS cannot accumulate rotation across iterations, so both tracks
are unrolled into explicit keyframes between the GENERATED markers.

    python scripts/wayfinder-ticks.py
"""

from __future__ import annotations

import re
from pathlib import Path

CSS = Path(__file__).resolve().parent.parent / "client/src/styles/wayfinder.css"

STEP = 6  # degrees per tick
# Ease for one tick: quick start, ~6% overshoot (~0.35deg), settle.
TICK_EASE = "cubic-bezier(0.3, 1.45, 0.55, 1)"

IDLE_SECONDS = 60  # one tick per second; keep in sync with wf-tick in wayfinder.css
IDLE_MOVE = 0.13  # seconds each idle tick takes to travel

SPIN_SECONDS = 2.2  # keep in sync with .wayfinder-chassis-spin in wayfinder.css
SPIN_TICKS = 120  # two full turns, so a remount lands on the same face
SPIN_MOVE_MAX = 0.11  # seconds; shortened when ticks come faster than this
SPIN_CURVE = (0.8, 1.8)  # speed v(u) = u^a (1-u)^b: hard spin-up, long settle


def spin_tick_starts() -> list[float]:
    """Fractions of the spin at which each tick begins moving."""
    a, b = SPIN_CURVE
    n = 20000
    speed = [(i / n) ** a * (1 - i / n) ** b for i in range(n + 1)]
    area = [0.0]
    for i in range(n):
        area.append(area[-1] + (speed[i] + speed[i + 1]) / 2)
    starts, tick = [], 0
    for i, value in enumerate(area):
        while tick < SPIN_TICKS and value / area[-1] >= tick / SPIN_TICKS:
            starts.append(i / n)
            tick += 1
    return starts


def keyframes(name: str, ticks: list[tuple[float, float]]) -> str:
    """ticks: (start, move) as fractions of the animation."""
    frames = [] if ticks[0][0] == 0 else ["0% { transform: rotate(0deg); }"]
    for index, (start, move) in enumerate(ticks):
        angle = index * STEP
        frames.append(
            f"{start * 100:.3f}% {{ transform: rotate({angle}deg); animation-timing-function: {TICK_EASE}; }}"
        )
        frames.append(f"{(start + move) * 100:.3f}% {{ transform: rotate({angle + STEP}deg); }}")
    if sum(ticks[-1]) < 1 - 1e-9:
        frames.append(f"100% {{ transform: rotate({len(ticks) * STEP}deg); }}")
    body = "\n".join(f"  {frame}" for frame in frames)
    return f"@keyframes {name} {{\n{body}\n}}"


def main() -> None:
    idle_move = IDLE_MOVE / IDLE_SECONDS
    # Each tick lands on the second, so the last one lands exactly at 100%.
    idle = [((i + 1) / IDLE_SECONDS - idle_move, idle_move) for i in range(IDLE_SECONDS)]

    starts = spin_tick_starts()
    # Scale so the last tick finishes its move exactly at 100% (the ring "sets").
    move_max = SPIN_MOVE_MAX / SPIN_SECONDS
    scale = (1 - move_max) / starts[-1]
    starts = [s * scale for s in starts]
    spin = []
    for i, start in enumerate(starts):
        if i + 1 == len(starts):
            spin.append((start, 1 - start))
        else:
            spin.append((start, min(move_max, (starts[i + 1] - start) * 0.85)))

    generated = "\n".join([
        "/* GENERATED by scripts/wayfinder-ticks.py - edit the script, not these frames. */",
        keyframes("wf-tick", idle),
        keyframes("wf-inner-spin", spin),
        "/* END GENERATED */",
    ])
    css = CSS.read_text(encoding="utf-8")
    pattern = re.compile(r"/\* GENERATED by scripts/wayfinder-ticks\.py.*?/\* END GENERATED \*/", re.S)
    if not pattern.search(css):
        raise SystemExit("GENERATED markers not found in wayfinder.css")
    CSS.write_text(pattern.sub(lambda _: generated, css), encoding="utf-8")
    print(f"Wrote {len(idle)} idle + {len(spin)} spin ticks")


if __name__ == "__main__":
    main()
